---
services:
  chall:
    build: .
    restart: unless-stopped
    environment:
      FLAG: snakeCTF{4n0n_byp4553d_th3_f1lt3r_4543ad7fe7e2f82a}
      LOG_SOLVE: 1
    ports:
      - "3000:3000"
    read_only: true
    volumes:
      - type: tmpfs
        target: /tmp