---
services:
  app:
    build: .
    restart: unless-stopped
    read_only: true
    ports:
      - 3000:3000
    volumes:
      - type: tmpfs
        target: /tmp
    environment:
      NODE_ENV: production
      DB_PATH: /tmp/database.db